//
//  AddToDoTaskModels.swift
//  CleanSwiftExample
//
//  Created by Diego Fonseca Marín on 6/6/17.
//  Copyright (c) 2017 Diego Fonseca Marín. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct AddToDoTask{
    struct Request{
    }
    
    struct Response{
    }
    
    struct ViewModel{
    }
}

