//
//  AddToDoTaskViewController.swift
//  CleanSwiftExample
//
//  Created by Diego Fonseca Marín on 6/6/17.
//  Copyright (c) 2017 Diego Fonseca Marín. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AddToDoTaskViewControllerInput{
    func displaySomething(viewModel: AddToDoTask.ViewModel)
}

protocol AddToDoTaskViewControllerOutput{
    func doSomething(request: AddToDoTask.Request)
}

class AddToDoTaskViewController: UIViewController, AddToDoTaskViewControllerInput{
    var output: AddToDoTaskViewControllerOutput!
    var router: AddToDoTaskRouter!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib(){
        super.awakeFromNib()
        AddToDoTaskConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad(){
        super.viewDidLoad()
        doSomethingOnLoad()
    }
    
    // MARK: Event handling
    
    func doSomethingOnLoad(){
        // NOTE: Ask the Interactor to do some work
        
        let request = AddToDoTask.Request()
        output.doSomething(request: request)
    }
    
    // MARK: Display logic
    
    func displaySomething(viewModel: AddToDoTask.ViewModel){
        // NOTE: Display the result from the Presenter
        
        // nameTextField.text = viewModel.name
    }
}
